services:
  mongo:
    image: mongo:7.0
    container_name: qrss-mongo
    ports:
      - "27017:27017"
    volumes:
      - qrss-mongo:/data/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  qrss-mongo:
